name: Build and Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Install Dependencies
      run: |
        sudo apt update 
        sudo apt install mesa-utils libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload
      # Upload the built executable for each platform
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.platform}}
        path:
          ${{github.workspace}}/build/bin/${{env.BUILD_TYPE}}/**/main*
