name: Build and Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Install Dependencies
      run: |
        sudo apt update 
        sudo apt install xorg-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path:
          ${{github.workspace}}/build/bin/${{env.BUILD_TYPE}}/main

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path:
          ${{github.workspace}}/build/bin/${{env.BUILD_TYPE}}/${{env.BUILD_TYPE}}/main.exe
          
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: macOS
        path:
          ${{github.workspace}}/build/bin/${{env.BUILD_TYPE}}/main
