name: Build and Upload

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Install Dependencies
      run: sudo apt update & sudo apt install libxrandr-dev & sudo apt install libxinerama-dev & sudo apt install libxcursor-dev & sudo apt install libxi-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload
      # Upload the built executable for each platform
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.platform}}
        # Windows uses the .exe extension and uses an extra directory named after the build type, MacOS and Linux do not
        path:
          ${{github.workspace}}/build/bin/${{env.BUILD_TYPE}}/**/main*
